---
homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include configuration/customize.yaml

frontend:

http:
  api_password: !secret api_password

config:

updater:

conversation:

history:

logbook:

map:

sun:

ios:

wake_on_lan:

# Text To Speech
tts:
  - platform: google
    language: nl
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# InfluxDB
influxdb:
  host: 127.0.0.1
  port: 8086
  database: hass

# MQTT
mqtt:
  broker: 127.0.0.1
  client_id: home-assistant
  keepalive: 60
  birth_message:
    topic: 'ha/hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'ha/hass/status'
    payload: 'offline'
    qos: 1
    retain: true

# BMW
#bmw_connected_drive:
#  bmw:
#    username: !secret bmw_username
#    password: !secret bmw_password
#    region: rest_of_world

# Zwave 
zwave:
  usb_path: /dev/ttyACM0
  device_config: !include configuration/zwave_device_config.yaml

script:
  sonos_speak:
    sequence:
    - service: media_player.sonos_snapshot
      data_template:
        entity_id: media_player.kantoor
    - service: media_player.sonos_unjoin
      data_template:
        entity_id: media_player.kantoor
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.kantoor
        volume_level: 0.40
    - service: tts.google_say
      data_template:
        entity_id: media_player.kantoor
        message: "Er staat iemand voor de deur."
    - delay: "00:00:05"
    - service: media_player.sonos_restore
      data_template:
        entity_id: media_player.kantoor

sensor: !include configuration/sensor.yaml 
switch: !include configuration/switch.yaml
group: !include configuration/group.yaml
zone: !include configuration/zone.yaml
scene: !include configuration/scene.yaml
automation: !include_dir_merge_list configuration/automation/
input_boolean: !include configuration/input_boolean.yaml
input_select: !include configuration/input_select.yaml
notify: !include configuration/notify.yaml
device_tracker: !include configuration/device_tracker.yaml
sonos: !include configuration/sonos.yaml
media_player: !include configuration/media_player.yaml
