---
homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include configuration/customize.yaml

frontend:

lovelace:
  mode: yaml

recorder:
  db_url: !secret db_url

config:

updater:

conversation:

history:

logbook:

map:

sun:

mobile_app:

wake_on_lan:

system_health:

# Text To Speech
tts:
  - platform: google_translate
    service_name: google_say
    language: nl
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# MQTT
mqtt:
  broker: !secret mqtt_host
  client_id: home-assistant
  keepalive: 60
  birth_message:
    topic: 'ha/hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'ha/hass/status'
    payload: 'offline'
    qos: 1
    retain: true

# BMW
bmw_connected_drive:
  bmw:
    username: !secret bmw_username
    password: !secret bmw_password
    region: rest_of_world
    
# WebOS TV
webostv:
  host: !secret tv_host
  name: 'TV Living Room'
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: '04-4E-AF-32-52-84'
      
# HEOS
heos:
  host: !secret heos_host

# Zwave 
zwave:
  usb_path: /dev/ttyACM0

group: !include configuration/group.yaml
sensor: !include configuration/sensor.yaml 
switch: !include configuration/switch.yaml
zone: !include configuration/zone.yaml
scene: !include configuration/scene.yaml
automation: !include_dir_merge_list configuration/automation/
input_boolean: !include configuration/input_boolean.yaml
input_select: !include configuration/input_select.yaml
notify: !include configuration/notify.yaml
unifi: !include configuration/unifi.yaml
sonos: !include configuration/sonos.yaml
media_player: !include configuration/media_player.yaml