title: Thuis
views:

### DASHBOARD ###
  - title: Dashboard
    path: dashboard
    icon: mdi:home
    cards:

      - title: Scenes
        type: entities
        show_header_toggle: false
        entities:
          - scene.leaving

      - title: Instellingen
        type: entities
        show_header_toggle: false
        entities:
          - input_boolean.night_mode

      - title: Weer
        type: entities
        show_header_toggle: false
        entities:
          - weather.buienradar
          - sensor.buienradar_temperature
          - sensor.buienradar_symbol
          - sensor.buienradar_humidity
          - sensor.buienradar_pressure
          - sensor.buienradar_wind_speed
          - sun.sun
          - camera.buienradar

      - title: Verwarming
        type: thermostat
        entity: climate.downstairs

      - title: Personen
        type: entities
        show_header_toggle: false
        entities:
          - group.tracker_kevin
          - group.tracker_amrita

      - title: Auto
        type: entities
        show_header_toggle: false
        entities:
          - device_tracker.kevster_location_tracker
          - lock.kevster_door_lock
          - sensor.kevster_battery_sensor
          - binary_sensor.kevster_charger_sensor
          - sensor.kevster_charging_rate_sensor
          - sensor.kevster_range_sensor
          - sensor.kevster_temperature_sensor_inside
          - sensor.kevster_temperature_sensor_outside
          - sensor.kevster_mileage_sensor
          - climate.kevster_hvac_climate_system

      - title: Afval
        type: entities
        show_header_toggle: false
        entities:
          - sensor.avri_wastecollector_vandaag
          - sensor.avri_wastecollector_morgen
          - sensor.avri_wastecollector_gft
          - sensor.avri_wastecollector_papier
          - sensor.avri_wastecollector_pmd

      - title: Systeem
        type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.docker_hub_update_available
            name: Update beschikbaar
          - entity: sensor.current_version
            name: Huidige versie
          - entity: sensor.docker_hub
            name: Nieuwste versie
          - type: button
            name: Reload automations
            action_name: Reload
            tap_action:
              action: call-service
              service: automation.reload
          - type: button
            name: Reload scenes
            action_name: Reload
            tap_action:
              action: call-service
              service: scene.reload
          - type: button
            name: Restart Home Assistant
            action_name: Restart
            tap_action:
              action: call-service
              service: homeassistant.restart

### DOWNSTAIRS ###
  - title: Beneden
    path: downstairs
    cards:

      - title: Woonkamer
        type: entities
        show_header_toggle: true
        entities:
          - scene.downstairs_living_evening
          - scene.downstairs_living_watchtv
          - binary_sensor.downstairs_living_multi_motion
          - sensor.downstairs_living_multi_temperature
          - sensor.downstairs_living_multi_luminance
          - sensor.downstairs_living_multi_battery
          - light.downstairs_living
          - light.downstairs_living_couch
          - light.downstairs_living_dresser
          - light.downstairs_living_tv
          - media_player.tv_living_room
          - media_player.heos_bar
          - media_player.kodi

      - title: Keuken
        type: entities
        show_header_toggle: true
        entities:
          - light.downstairs_kitchen
          - light.downstairs_dining
          - media_player.keuken

      - title: Hal
        type: entities
        show_header_toggle: true
        entities:
          - light.downstairs_hallway
          - binary_sensor.downstairs_hallway_frontdoor

      - title: Tuin
        type: entities
        show_header_toggle: true
        entities:
          - light.downstairs_frontyard_door
          - light.downstairs_frontyard_garage_left
          - light.downstairs_frontyard_garage_right
          - switch.downstairs_backyard_light
          - switch.downstairs_backyard_tile_lights

      - title: Kerstverlichting
        type: entities
        show_header_toggle: True
        entities:
          - switch.downstairs_living_christmastree
          - switch.downstairs_dining_christmastree
          - switch.downstairs_frontyard_christmas_lights
          - switch.downstairs_backyard_christmas_lights

      - title: HEOS
        type: media-control
        entity: media_player.heos_bar

      - title: TV
        type: media-control
        entity: media_player.tv_living_room

      - title: Kodi
        type: media-control
        entity: media_player.kodi

      - title: Voordeur
        type: picture-glance
        entities:
          - binary_sensor.voordeur_doorbell
          - binary_sensor.voordeur_motion
          - binary_sensor.voordeur_is_dark
        camera_image: camera.voordeur_high
        camera_view: live

      - title: Oprit
        type: picture-glance
        entities:
          - binary_sensor.oprit_motion
          - binary_sensor.oprit_is_dark
        camera_image: camera.oprit_high
        camera_view: live

### UPSTAIRS ###
  - title: Boven
    path: upstairs
    cards:

      - title: Overloop
        type: entities
        show_header_toggle: True
        entities:
          - binary_sensor.upstairs_corridor_multi_motion
          - sensor.upstairs_corridor_multi_temperature
          - sensor.upstairs_corridor_multi_luminance
          - sensor.upstairs_corridor_multi_battery
          - light.upstairs_corridor

      - title: Kantoor
        type: entities
        show_header_toggle: true
        entities:
          - media_player.kantoor

      - title: SONOS
        type: media-control
        entity: media_player.kantoor

### ATTIC ###
  - title: Zolder
    path: attic
    cards:

      - title: Washok
        type: entities
        show_header_toggle: false
        entities:
          - sensor.washing_machine_status
          - sensor.ventilation_status

      - title: Afzuiging
        type: entities
        show_header_toggle: false
        entities:
          - fan.attic_ventilation
          - sensor.attic_ventilation_speed
          - sensor.attic_ventilation_speed_rpm

### HOUSE ###
  - title: Huis
    path: house
    cards:

      - title: Verbruik
        type: entities
        show_header_toggle: false
        entities:
          - sensor.power_usage
          - sensor.power_usage_low
          - sensor.power_usage_high
          - sensor.power_tariff
          - sensor.power_generated
          - sensor.power_generated_low
          - sensor.power_generated_high
          - sensor.gas_usage
          - sensor.water_usage

      - title: Dag verbruik
        type: entities
        show_header_toggle: false
        entities:
          - sensor.power_day_usage
          - sensor.power_day_usage_low
          - sensor.power_day_usage_high
          - sensor.power_day_generated
          - sensor.power_day_generated_low
          - sensor.power_day_generated_high
          - sensor.gas_day_usage
          - sensor.water_day_usage
          - sensor.power_day_usage_cost
          - sensor.gas_day_usage_cost
          - sensor.energy_day_usage_cost

      - title: Verbruik apparaten
        type: entities
        show_header_toggle: false
        entities:
          - sensor.fusebox_server_usage
          - sensor.kitchen_espressomachine_usage
          - sensor.garage_freezer_usage
          - sensor.garage_refrigerator_usage
          - sensor.attic_washingmachine_usage
          - sensor.attic_heating_usage
          - sensor.upstairs_bedroom_charger_kevin
