---
# Buienradar
- platform: buienradar
  monitored_conditions:
    - symbol
    - humidity
    - temperature
    - windspeed
    - pressure
    - condition
      
# Smartmeter
- platform: mqtt
  name: power_usage
  state_topic: ha/sensor/smartmeter/electricity/current-watt
  unit_of_measurement: kWh
    
- platform: mqtt
  name: power_usage_low
  state_topic: ha/sensor/smartmeter/electricity/kwh-low
  unit_of_measurement: kWh
    
- platform: mqtt
  name: power_usage_high
  state_topic: ha/sensor/smartmeter/electricity/kwh-high
  unit_of_measurement: kWh
    
- platform: mqtt
  name: power_generated_low
  state_topic: ha/sensor/smartmeter/electricity/kwh-generated-low
  unit_of_measurement: kWh
    
- platform: mqtt
  name: power_generated_high
  state_topic: ha/sensor/smartmeter/electricity/kwh-generated-high
  unit_of_measurement: kWh
    
- platform: mqtt
  name: gas_usage
  state_topic: ha/sensor/smartmeter/gas/m3
  unit_of_measurement: m3
  
# Plugwise
- platform: mqtt
  name: fusebox_server_usage
  state_topic: 'plugwise2py/state/power/000D6F0001A44529'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'
  
- platform: mqtt
  name: kitchen_dishwasher_usage
  state_topic: 'plugwise2py/state/power/000D6F000397AAAE'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'
  
- platform: mqtt
  name: attic_freezer_usage
  state_topic: 'plugwise2py/state/power/000D6F0003979084'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'
  
- platform: mqtt
  name: attic_washingmachine_usage
  state_topic: 'plugwise2py/state/power/000D6F00004EF088'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'
  
- platform: mqtt
  name: attic_ventilation_usage
  state_topic: 'plugwise2py/state/power/000D6F000397465D'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'
  
- platform: mqtt
  name: attic_heating_usage
  state_topic: 'plugwise2py/state/power/000D6F00039791E0'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'
  
- platform: mqtt
  name: upstairs_bedroom_charger_kevin
  state_topic: 'plugwise2py/state/power/000D6F00001C7B58'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'
  
- platform: mqtt
  name: upstairs_bedroom_charger_amrita
  state_topic: 'plugwise2py/state/power/000D6F000038BF7A'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'
  
# Appliances
- platform: template
  sensors:
    washing_machine_status:
      value_template: '{{ states.input_select.washing_machine_status.state}}'
      
- platform: template
  sensors:
    ventilation_status:
      value_template: '{{ states.input_select.ventilation_status.state}}'