---
# Version
- platform: version

# Buienradar
- platform: buienradar
  monitored_conditions:
    - symbol
    - humidity
    - temperature
    - windspeed
    - pressure
    - condition

# Smartmeter readings
- platform: mqtt
  name: power_usage
  state_topic: dsmr/reading/electricity_currently_delivered
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_usage_low
  state_topic: dsmr/reading/electricity_delivered_1
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_usage_high
  state_topic: dsmr/reading/electricity_delivered_2
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_tariff
  state_topic: dsmr/meter-stats/electricity_tariff
  value_template: '{% if value | int == 1 %}Laag{% elif value | int == 2 %}Hoog{% else %}Onbekend{% endif %}'

- platform: mqtt
  name: power_generated
  state_topic: dsmr/reading/electricity_currently_returned
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_generated_low
  state_topic: dsmr/reading/electricity_returned_1
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_generated_high
  state_topic: dsmr/reading/electricity_returned_2
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: gas_usage
  state_topic: dsmr/reading/extra_device_delivered
  unit_of_measurement: m3
  value_template: '{{ value | float }}'

# Smartmeter day consumption
- platform: mqtt
  name: power_day_usage
  state_topic: dsmr/day-consumption/electricity_merged
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_day_usage_low
  state_topic: dsmr/day-consumption/electricity1
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_day_usage_high
  state_topic: dsmr/day-consumption/electricity2
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_day_usage_cost
  state_topic: dsmr/day-consumption/electricity_cost_merged
  unit_of_measurement: EUR
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_day_usage_low_cost
  state_topic: dsmr/day-consumption/electricity1_cost
  unit_of_measurement: EUR
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_day_usage_high_cost
  state_topic: dsmr/day-consumption/electricity2_cost
  unit_of_measurement: EUR
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_day_generated
  state_topic: dsmr/day-consumption/electricity_returned_merged
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_day_generated_low
  state_topic: dsmr/day-consumption/electricity1_returned
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: power_day_generated_high
  state_topic: dsmr/day-consumption/electricity2_returned
  unit_of_measurement: kWh
  value_template: '{{ value | float }}'

- platform: mqtt
  name: gas_day_usage
  state_topic: dsmr/day-consumption/gas
  unit_of_measurement: m3
  value_template: '{{ value | float }}'

- platform: mqtt
  name: gas_day_usage_cost
  state_topic: dsmr/day-consumption/gas_cost
  unit_of_measurement: EUR
  value_template: '{{ value | float }}'

- platform: mqtt
  name: energy_day_usage_cost
  state_topic: dsmr/day-consumption/total_cost
  unit_of_measurement: EUR
  value_template: '{{ value | float }}'

# Watermeter
- platform: mqtt
  name: water_usage
  state_topic: watermeter/reading
  unit_of_measurement: m3
  value_template: '{{ value | float }}'

# Plugwise
- platform: mqtt
  name: fusebox_server_usage
  state_topic: 'plugwise2py/state/power/000D6F0001A44529'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'

- platform: mqtt
  name: kitchen_espressomachine_usage
  state_topic: 'plugwise2py/state/power/000D6F000397AAEF'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'

- platform: mqtt
  name: garage_freezer_usage
  state_topic: 'plugwise2py/state/power/000D6F0003979084'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'

- platform: mqtt
  name: garage_refrigerator_usage
  state_topic: 'plugwise2py/state/power/000D6F00004ED25A'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'

- platform: mqtt
  name: attic_washingmachine_usage
  state_topic: 'plugwise2py/state/power/000D6F00004EF088'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'

- platform: mqtt
  name: attic_heating_usage
  state_topic: 'plugwise2py/state/power/000D6F00025F6796'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'

- platform: mqtt
  name: upstairs_bedroom_charger_kevin
  state_topic: 'plugwise2py/state/power/000D6F00001C7B58'
  unit_of_measurement: 'W'
  value_template: '{{ value_json.power if value_json.power > 0 else 0 }}'

# ITHO
- platform: mqtt
  name: attic_ventilation_speed
  state_topic: 'itho/ithostatus'
  unit_of_measurement: 'W'
  value_template: "{{ value_json['Speed Status'] }}"

- platform: mqtt
  name: attic_ventilation_speed_rpm
  state_topic: 'itho/ithostatus'
  unit_of_measurement: 'W'
  value_template: "{{ value_json['Fan speed (rpm)'] }}"

# Appliances
- platform: template
  sensors:
    washing_machine_status:
      value_template: '{{ states.input_select.washing_machine_status.state}}'

- platform: template
  sensors:
    ventilation_status:
      value_template: '{{ states.input_select.ventilation_status.state}}'

# Afvalbeheer
- platform: afvalbeheer
  name: wastecollector
  wastecollector: Avri
  resources:
    - gft
    - papier
    - pmd
  postcode: !secret home_zipcode
  streetnumber: !secret home_streetnumber
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 0
  dateobject: 0
  dayofweek: 1
  nameprefix: 1
  builtinicons: 0
  disableicons: 1
  dutch: 1
  updateinterval: 1
