---
- platform: mqtt
  name: bedroom_lamp_tv
  optimistic: False
  command_topic: 'plugwise2py/cmd/switch/000D6F000059A9F1'
  state_topic: 'plugwise2py/state/circle/000D6F000059A9F1'
  value_template: '{"mac": "000D6F000059A9F1", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F000059A9F1", "cmd": "switch", "val": "on"}'
  payload_off: '{"mac": "000D6F000059A9F1", "cmd": "switch", "val": "off"}'
  retain: True
  
- platform: mqtt
  name: office_lamp_desk
  optimistic: False
  command_topic: 'plugwise2py/cmd/switch/000D6F00004ED25A'
  state_topic: 'plugwise2py/state/circle/000D6F00004ED25A'
  value_template: '{"mac": "000D6F00004ED25A", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F00004ED25A", "cmd": "switch", "val": "on"}'
  payload_off: '{"mac": "000D6F00004ED25A", "cmd": "switch", "val": "off"}'
  retain: True