---
- platform: mqtt
  name: bedroom_lamp_tv
  optimistic: False
  command_topic: 'plugwise2py/cmd/switch/000D6F000059A9F1'
  state_topic: 'plugwise2py/state/circle/000D6F000059A9F1'
  value_template: '{"mac": "000D6F000059A9F1", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F000059A9F1", "cmd": "switch", "val": "on"}'
  payload_off: '{"mac": "000D6F000059A9F1", "cmd": "switch", "val": "off"}'
  retain: True

- platform: mqtt
  name: office_lamp_desk
  optimistic: False
  command_topic: 'plugwise2py/cmd/switch/000D6F00004ED25A'
  state_topic: 'plugwise2py/state/circle/000D6F00004ED25A'
  value_template: '{"mac": "000D6F00004ED25A", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F00004ED25A", "cmd": "switch", "val": "on"}'
  payload_off: '{"mac": "000D6F00004ED25A", "cmd": "switch", "val": "off"}'
  retain: True

- platform: mqtt
  name: downstairs_living_christmastree
  optimistic: False
  command_topic: 'plugwise2py/cmd/switch/000D6F000397470B'
  state_topic: 'plugwise2py/state/circle/000D6F000397470B'
  value_template: '{"mac": "000D6F000397470B", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F000397470B", "cmd": "switch", "val": "on"}'
  payload_off: '{"mac": "000D6F000397470B", "cmd": "switch", "val": "off"}'
  retain: True

- platform: mqtt
  name: downstairs_frontyard_christmas_lights
  optimistic: False
  command_topic: 'plugwise2py/cmd/switch/000D6F00039791BC'
  state_topic: 'plugwise2py/state/circle/000D6F00039791BC'
  value_template: '{"mac": "000D6F00039791BC", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F00039791BC", "cmd": "switch", "val": "on"}'
  payload_off: '{"mac": "000D6F00039791BC", "cmd": "switch", "val": "off"}'

- platform: mqtt
  name: downstairs_backyard_christmas_lights
  state_topic: "tasmota/sonoff01/stat/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "tasmota/sonoff01/cmnd/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tasmota/sonoff01/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
