---
- platform: mqtt
  name: downstairs_dining_christmastree
  optimistic: False
  command_topic: 'shellies/shelly01/relay/0/command'
  state_topic: 'shellies/shelly01/relay/0'
  json_attributes_topic: 'shellies/shelly01/info'
  payload_on: 'on'
  payload_off: 'off'
  retain: True

- platform: mqtt
  name: downstairs_living_christmastree
  optimistic: False
  command_topic: 'shellies/shelly02/relay/0/command'
  state_topic: 'shellies/shelly02/relay/0'
  json_attributes_topic: 'shellies/shelly02/info'
  payload_on: 'on'
  payload_off: 'off'
  retain: True

- platform: mqtt
  name: downstairs_backyard_christmas_lights
  state_topic: "tasmota/sonoff01/stat/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "tasmota/sonoff01/cmnd/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tasmota/sonoff01/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
