---
- alias: 'Activate silence mode on bedroom AC when home and is on'
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.people
        state: home
      - condition: state
        entity_id: climate.slaapkamer
        state: cool
  action:
    - service: climate.set_fan_mode
      entity_id: climate.slaapkamer
      data:
        fan_mode: Silence

- alias: 'Turn off bedroom AC at 02:00 when it is on'
  initial_state: on
  trigger:
    - platform: time
      at: '02:00'
  condition:
    - condition: state
      entity_id: climate.slaapkamer
      state: cool
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.slaapkamer
      data:
        hvac_mode: off