---
- alias: Dishwasher done
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_dishwasher_usage
    below: 5
    for:
      minutes: 1
  
  action:
    service: notify.email_kevin
    data:
      message: "Vaatwasser is klaar"
      title: "Vaatwasser is klaar"
      
- alias: Washingmachine done
  trigger:
    platform: numeric_state
    entity_id: sensor.attic_washingmachine_usage
    below: 5
    for:
      minutes: 1
  
  action:
    service: notify.email_kevin
    data:
      message: "Wasmachine is klaar"
      title: "Wasmachine is klaar"