---
- alias: 'Garden lights on when sunset'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: switch.turn_on
      data:
        entity_id: 
          - switch.lamp_garden_backyard
      
- alias: 'Garden lights off when sunrise'
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: switch.turn_off
      data:
        entity_id: 
          - switch.lamp_garden_backyard
