---
- alias: 'Garden lights on when sunset'
  initial_state: on
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:15:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: 
          - switch.downstairs_frontyard_light
          - switch.downstairs_backyard_light
      
- alias: 'Garden lights off when sunrise'
  initial_state: on
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.downstairs_frontyard_light
          - switch.downstairs_backyard_light
