---
- alias: 'Hallway lights on when front door opened and sunset'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.downstairs_hallway_frontdoor
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:45:00"
      - condition: state
        entity_id: group.people
        state: not_home
        for:
          minutes: 5
  action:
    - service: light.turn_on
      data:
        entity_id: light.downstairs_hallway
        brightness: 255