---
- alias: 'Living room lights on when sunset and presence'
  initial_state: on
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: group.people
    state: home
  action:
    service: scene.turn_on
    entity_id: scene.downstairs_living_evening

- alias: 'Living room lights coming home and sunset'
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.people
      to: 'home'
    - platform: state
      entity_id: binary_sensor.downstairs_hallway_frontdoor
      from: 'off'
      to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:45:00"
  action:
    service: scene.turn_on
    entity_id: scene.downstairs_living_evening

- alias: 'Living room lights to TV mode when TV turned on'
  initial_state: on
  trigger:
    platform: state
    entity_id: media_player.tv_living_room
    to: 'on'
    from: 'off'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:45:00"
  action:
    service: scene.turn_on
    entity_id: scene.woonkamer_tv

- alias: 'Living room lights to evening mode when TV turned off'
  initial_state: on
  trigger:
    platform: state
    entity_id: media_player.tv_living_room
    to: 'off'
    from: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:45:00"
  action:
    service: scene.turn_on
    entity_id: scene.woonkamer_gedimd

- alias: 'Kitchen lights on before sunrise'
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  condition:
    - condition: state
      entity_id: group.people
      state: home
    - condition: sun
      before: sunrise
  action:
    service: scene.turn_on
    entity_id: scene.downstairs_living_morning

- alias: 'Kitchen lights off at sunrise'
  initial_state: on
  trigger:
    platform: sun
    event: sunrise
  condition:
    - condition: state
      entity_id: group.people
      state: home
  action:
    service: scene.turn_on
    entity_id: scene.downstairs_living_morning_sunrise