---
- alias: 'Living room lights on when sunset and presence'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: home
  action:
    service: scene.turn_on
    entity_id: scene.downstairs_living_evening
    
- alias: 'Living room lights coming home and sunset'
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'home'
    for:
      minutes: 1
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:45:00"
  action:
    service: scene.turn_on
    entity_id: scene.downstairs_living_evening

- alias: 'Living room lights to TV mode when TV turned on'
  trigger:
    platform: state
    entity_id: media_player.tv_living_room
    to: 'playing'
    from: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.downstairs_living_watchtv

- alias: 'Living room lights to evening mode when TV turned off'
  trigger:
    platform: state
    entity_id: media_player.tv_living_room
    to: 'off'
    from: 'playing'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:45:00"
  action:
    service: scene.turn_on
    entity_id: scene.downstairs_living_evening
