---
- alias: 'Activate night mode when charging phone'
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.phone_charging_kevin
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.people
        state: home
      - condition: time
        after: '20:00:00'
        before: '04:00:00'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.night_mode

- alias: 'Activate night mode scene when night mode is enabled'
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.night_mode
    - service: notify.ios_iphonekevin_app
      data:
        title: 'Nachtmodus'
        message: 'Nachtmodus is ingeschakeld'

- alias: 'Deactivate night mode on workday'
  initial_state: on
  trigger:
    - platform: time
      at: '7:00:00'
  condition:
    - condition: time
      after: '7:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.night_mode

- alias: 'Deactivate night mode in weekend'
  initial_state: on
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    - condition: time
      after: '10:00:00'
      weekday:
        - sat
        - sun
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.night_mode
