---
- alias: 'Leaving'
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.people
      to: 'not_home'
      for:
        minutes: 5
  action:
    service: scene.turn_on
    entity_id: scene.leaving

- alias: 'Coming home'
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.people
      to: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.coming_home