---
- alias: 'Leaving'
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
      for:
        minutes: 5
  action:
    service: scene.turn_on
    entity_id: scene.leaving
