---
- alias: 'Thermostat at day mode when home'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  condition:
    - condition: state
      entity_id: group.people
      state: home
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.downstairs
      data:
        temperature: 21

- alias: 'Thermostat at night mode when home'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  condition:
    - condition: state
      entity_id: group.people
      state: home
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.downstairs
      data:
        temperature: 16

- alias: 'Thermostat off when temperature forecast is above 10 degrees'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  condition:
    - condition: state
      entity_id: group.people
      state: home
    - platform: numeric_state
      entity_id: sensor.buienradar_temperature_1d
      above: 9.99
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.downstairs

- alias: 'Thermostat on when temperature forecast is below 10 degrees'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  condition:
    - condition: state
      entity_id: group.people
      state: home
    - platform: numeric_state
      entity_id: sensor.buienradar_temperature_1d
      below: 10
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.downstairs

- alias: 'Thermostat off when leaving'
  trigger:
    - platform: state
      entity_id: group.people
      to: 'not_home'
      for:
        minutes: 5
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.downstairs

- alias: 'Thermostat on when coming home and forecast is below 10 degrees'
  trigger:
    - platform: state
      entity_id: group.people
      to: 'home'
  condition:
    - condition: numeric_state
      entity_id: sensor.buienradar_temperature_1d
      below: 10
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.downstairs

- alias: 'Thermostat at sunset and at home'
  initial_state: on
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: group.people
      state: home
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.downstairs