---
- alias: 'Upstairs corridor lights on at motion and dark'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.upstairs_corridor_multi_motion
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.people
        state: home
      - condition: numeric_state
        entity_id: sensor.upstairs_corridor_multi_luminance
        below: 60
  action:
    - service: light.turn_on
      data:
        entity_id: light.upstairs_corridor
        brightness: 255

- alias: 'Upstairs corridor lights off at no motion'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.upstairs_corridor_multi_motion
    from: 'on'
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.upstairs_corridor
