---
- alias: 'Ventilation to day mode'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  action:
    - service: fan.set_percentage
      target:
        entity_id: fan.attic_ventilation
      data:
        percentage: 20

- alias: 'Ventilation to night mode'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - service: fan.set_percentage
      target:
        entity_id: fan.attic_ventilation
      data:
        percentage: 8

- alias: 'Ventilation to high when showering'
  trigger:
    - platform: numeric_state
      entity_id: sensor.upstairs_bathroom_humidity
      above: 50
      for:
        minutes: 1
  action:
    - service: fan.set_percentage
      target:
        entity_id: fan.attic_ventilation
      data:
        percentage: 100

- alias: 'Ventilation to normal after showering'
  trigger:
    - platform: numeric_state
      entity_id: sensor.upstairs_bathroom_humidity
      below: 50
      for:
        minutes: 1
  action:
    - service: fan.set_percentage
      target:
        entity_id: fan.attic_ventilation
      data:
        percentage: 20