---
- alias: 'Ventilation to day mode'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  action:
    - service: fan.set_percentage
      target:
        entity_id: fan.attic_ventilation
      data:
        percentage: 20

- alias: 'Ventilation to night mode'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - service: fan.set_percentage
      target:
        entity_id: fan.attic_ventilation
      data:
        percentage: 8