---
- alias: 'Send alert for water usage during absence'
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.water_usage
  condition:
    - condition: state
      entity_id: group.people
      state: not_home
  action:
    - service: notify.ios_iphonekevin_app
      data:
        title: 'Waterverbruik'
        message: 'Er wordt water verbruikt, maar er is niemand thuis!'